SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE expense_shares;
TRUNCATE TABLE expenses;
TRUNCATE TABLE settlements;
TRUNCATE TABLE group_members;
TRUNCATE TABLE groups;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;